# Generated by Django 5.0.2 on 2024-02-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_membership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Member',
        ),
    ]
